title: My Journey as a developer
author: GitHub User
email: waieresanara@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
theme: minima

# social links
twitter_username: waieresanara # DO NOT include the @ character, or else the build will fail!
github_username:  warami13 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage


